# Generated by Django 3.2.4 on 2021-07-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20210704_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='desc',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=500),
        ),
    ]
