# Generated by Django 3.2.4 on 2021-06-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fldUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_loc_latit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_loc_longi',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='thumb_down',
        ),
        migrations.AddField(
            model_name='profile',
            name='emp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lat-Long'),
        ),
    ]
