# Generated by Django 3.2.4 on 2021-06-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fldUser', '0002_auto_20210618_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='emp_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Emp Id'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Location'),
        ),
    ]
